- similarity
- dissimilarity

# 01. Minkowski distance 

## 1-1. Manhattan distance (L1)
동일한 차원의 값을 다 빼서 더한 것 

In [24]:
a = np.array([1,2,3])
b = np.array([-1,2,6])

dist = sum(abs(a-b))
dist

5

## 1-2. Euclidean distance (L2)
직선 거리 


In [2]:
# numpy 사용 
import numpy as np 
a = np.array([1,2,3])
b = np.array([4,5,6])

dist = np.linalg.norm(a-b)
print(dist)

5.196152422706632


In [3]:
# scipy 사용 
from scipy.spatial import distance 
print(distance.euclidean(a,b))

5.196152422706632


In [16]:
# 데이터프레임으로 거리 구해보기 
import pandas as pd 
df = pd.DataFrame({"a" : a, "b" : b})
df

a  b
0  1  4
1  2  5
2  3  6

In [22]:
dist = np.linalg.norm(df['a']-df['b'])
print(dist)

dist1 = np.linalg.norm(df.iloc[0]-df.iloc[1])
print(dist1)

dist2 = np.linalg.norm(np.array([1,4])- np.array([2,5]))
print(dist2)

5.196152422706632
1.4142135623730951
1.4142135623730951


## 1-3. Supremum distance (Lmax)
맨하탄 거리 중에서 제일 큰 놈만 남기고 나머지 다 죽임

# +) The properties of distances 

1) Positivity : 거리는 양수여야 함 
2) Symmetry : x,y (앞뒤)가 바뀌어도 똑같아야 함 
3) Triangle inequality : x에서 z로 가는 것보다 x,y,x로 가는 것이 더 길어야 함 

# 02. Similarity coefficients 
(상관성)

binary data 사용함

## 2-1 Simple Matching Coefficient

In [29]:
# simple matching coefficient 

x = np.array([1,0,0,1])
y = np.array([1,0,1,1])

# 똑같은 것이 몇 개니? 

def similarity (x,y) : 
    z = x - y 
    count = np.count_nonzero(z == 0)
    return count/len(z) 

similarity(x,y)

0.75

## 2-2 Jaccard coefficient 
존재하는 것만 세기 

ex) 아마존 같이 상품이 엄청 많으면 아무도 안 산 상품은 계산에서 제거하는 것 

In [37]:
x = np.array([1,0,0,0,0,0,1])
y = np.array([0,0,0,0,0,1,1])

f01, f10, f11 = 0, 0 , 0
for i in range(len(x)) : 
    if (x[i]==0) & (y[i]==1):
        f01 +=1 
    elif (x[i]==1) & (y[i]==0):
        f10 +=1
    elif (x[i]==1) & (y[i]==1)  : 
        f11 += 1 
f11/(f01+f10+f11)

0.3333333333333333

# 03. Cosine Similarity 
- 각도가 서로 붙으면? 값 최대화 
- 각도와 유사도는 반비례 

- 각도가 작다는 것은 서로 가까이 붙어있다는 것이니깐 유사도가 높은 것 

- 0~180 : 유사도가 작아짐 
- 180~360 : 유사도가 커짐 (다시 가까워지니깐)

**공식 : X 내적의 합 / 벡터 x의 길이**
- 내적이란? 똑같은 위치를 다 곱해서 더한 것 

In [ ]:
# a = np.random.randint(0,3,5)
# b = np.random.randint(0,3,5)
a = np.array([3,2,0,5,0,0,0,0,2,0,0])
b = np.array([1,0,0,0,0,0,0,0,1,0,2])
print(a,b)
mul = sum(a*b)
print(mul)

len_a = (sum(a**2))**(1/2)
len_b = (sum(b**2))**(1/2)

print(len_a,len_b)

cos = mul/(len_a*len_b)
print(cos)

[3 2 0 5 0 0 0 0 2 0 0] [1 0 0 0 0 0 0 0 1 0 2]
5
6.48074069840786 2.449489742783178
0.314970394174356


# 04. Correlation
- 2개의 attribute가 주어졌을 때, 값의 경향을 알고 싶은 것 
- 나열된 순서는 중요하지 않음 

## 4-1 Pearson's Correlation 

xy공분산 / (x 표준편차 * y 표준편차)

In [56]:
x = np.array([-3,6,0,3,-6])
y = np.array([1,-2,0,-1,2])
x,y

(array([-3,  6,  0,  3, -6]), array([ 1, -2,  0, -1,  2]))

In [57]:
df = pd.DataFrame({"x" : x, "y" : y})
df

x  y
0 -3  1
1  6 -2
2  0  0
3  3 -1
4 -6  2

In [59]:
# 표본평균 
x_bar = sum(df['x']) / len(df['x'])
y_bar = sum(df['y']) / len(df['y'])

# 편차
df['x_dev'] = df['x'] - x_bar 
df['y_dev'] = df['y'] - y_bar

# 편차 곱 
df['dev_mul'] = df['x_dev']*df['y_dev']

# 공분산 
cov=sum(df['dev_mul'])/(df.shape[0]-1)

# 표본표준편차 
x_stdev = (sum(df['x_dev']**2)/(df.shape[0]-1))**(1/2)
y_stdev = (sum(df['y_dev']**2)/(df.shape[0]-1))**(1/2)

#피어슨 상관계수 

pearson = cov/(x_stdev*y_stdev)
print(pearson)
df


-0.9999999999999999


x  y  x_dev  y_dev  dev_mul
0 -3  1   -3.0    1.0     -3.0
1  6 -2    6.0   -2.0    -12.0
2  0  0    0.0    0.0      0.0
3  3 -1    3.0   -1.0     -3.0
4 -6  2   -6.0    2.0    -12.0

## 실습 

In [69]:
x = np.array([1,2,4,3,0,0,0])
y = np.array([6,7,8,9,5,5,5])
# y= np.array([2,4,6,8,0,0,0])

In [70]:
# 코사인 데이터 

# 내적 / 벡터까지의 길이 

mul = sum(x*y)

x_len= (sum(x**2))**(1/2)
y_len= (sum(y**2))**(1/2)

cos = mul/(x_len*y_len)
print(cos)

0.8258792301131205


In [73]:
# 피어슨 상관계수 

# cov(x,y) / (stdev(x)*stdev(y))

df = pd.DataFrame({"x" : x, 'y' : y})

df.describe()


x         y
count  7.000000  7.000000
mean   1.428571  6.428571
std    1.618347  1.618347
min    0.000000  5.000000
25%    0.000000  5.000000
50%    1.000000  6.000000
75%    2.500000  7.500000
max    4.000000  9.000000

In [79]:
x_stdev = df['x'].std()
y_stdev = df['y'].std()
cov = df['x'].cov(df['y'])

corr = cov/(x_stdev*y_stdev)
corr

0.9363636363636361

In [81]:
# 유클리디안 거리 
from scipy.spatial import distance 

dist = distance.euclidean(df['x'], df['y'])
dist

13.30413469565007

보통 코사인 유사도는 짧은 글과 긴 글을 비교할 때 의미있다. 

왜냐하면, 코사인 거리는 길이에 좌지우지하지 않기 때문이다 

# 05. Issues in Proximity Calculation 

## 5-1. Standardization 

In [83]:
# Rescaling [0,1]

re_x = (x-min(x)) / (max(x)-min(x))

# mean normalization [-1,1]
norm_x = (x-x.mean()) / (max(x)-min(x))

# Standardization (정규분포)
stand_x = (x-x.mean()) / x.std()

re_x, norm_x, stand_x


(array([0.25, 0.5 , 1.  , 0.75, 0.  , 0.  , 0.  ]),
 array([-0.10714286,  0.14285714,  0.64285714,  0.39285714, -0.35714286,
        -0.35714286, -0.35714286]),
 array([-0.28603878,  0.38138504,  1.71623266,  1.04880885, -0.95346259,
        -0.95346259, -0.95346259]))

## 5-2 Using weights 